os:
  - linux
#  - osx
language: python
sudo: required
dist: trusty
env:
  - CONAN_COMPILER=gcc CONAN_COMPILER_VERSION=4.8
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements_server.txt
  - pip install -r requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export CONAN_LOGGING_LEVEL=10
# command to run tests
script: nosetests